package com.fajarwatitoyo.laimu;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DataKamus extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "dbkamus";
    public static final String INDONESIA = "indonesia";
    public static final String LAIMU = "laimu";

    public DataKamus(Context context) {
        super(context, DATABASE_NAME, null, 1);
    }

    public void createTable(SQLiteDatabase db) {
        db.execSQL("DROP TABLE IF EXISTS kamus");
        db.execSQL("CREATE TABLE if not exists kamus (id INTEGER PRIMARY KEY AUTOINCREMENT, indonesia TEXT, laimu TEXT);");
    }

    public void generateData(SQLiteDatabase db) {
        ContentValues cv = new ContentValues();

        //KATA DAN KALIMAT//
         //KATA//
        // A-LAIMU //
        cv.put(INDONESIA, "makanan");
        cv.put(LAIMU, "AAELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "makan");
        cv.put(LAIMU, "AE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "agama");
        cv.put(LAIMU, "AGAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "minggu");
        cv.put(LAIMU, "AHAD");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gubuk");
        cv.put(LAIMU, "AHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "akhirat");
        cv.put(LAIMU, "AKHIRATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ulat");
        cv.put(LAIMU, "AIYO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lendir");
        cv.put(LAIMU, "AKALAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "marbot");
        cv.put(LAIMU, "AKAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "flu");
        cv.put(LAIMU, "AKINONO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pucuk");
        cv.put(LAIMU, "AKUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hagus");
        cv.put(LAIMU, "ALAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bantal");
        cv.put(LAIMU, "ALAJUHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "benci");
        cv.put(LAIMU, "ALANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "istirahat");
        cv.put(LAIMU, "ALIE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perangkat desa");
        cv.put(LAIMU, "ALO ONO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menulis");
        cv.put(LAIMU, "ALUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "daun siri");
        cv.put(LAIMU, "AM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ibu");
        cv.put(LAIMU, "AMAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mama");
        cv.put(LAIMU, "AMAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bunda");
        cv.put(LAIMU, "AMAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menguap");
        cv.put(LAIMU, "AMAMOA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "selamat tinggal");
        cv.put(LAIMU, "AMATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cempedak");
        cv.put(LAIMU, "ANA ALO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nanas");
        cv.put(LAIMU, "ANANASU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nenek");
        cv.put(LAIMU, "ANENE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "paksa");
        cv.put(LAIMU, "ANSAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sumpah");
        cv.put(LAIMU, "ANSAYAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memanggil");
        cv.put(LAIMU, "APAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ayah");
        cv.put(LAIMU, "APAPA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bapak");
        cv.put(LAIMU, "APAPA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ludah");
        cv.put(LAIMU, "APE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "arap");
        cv.put(LAIMU, "ARAPI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang arab");
        cv.put(LAIMU, "ARAPILU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bungkusan");
        cv.put(LAIMU, "ARUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tadi");
        cv.put(LAIMU, "ASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengasa");
        cv.put(LAIMU, "ASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dari tadi");
        cv.put(LAIMU, "ASA KOLAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "adat");
        cv.put(LAIMU, "ATATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengantuk");
        cv.put(LAIMU, "ATATULU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kakek");
        cv.put(LAIMU, "ATETE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gunting");
        cv.put(LAIMU, "ATOLI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "paman");
        cv.put(LAIMU, "ATUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lansat");
        cv.put(LAIMU, "AULANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "duku");
        cv.put(LAIMU, "AULANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "globak");
        cv.put(LAIMU, "AULI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jambu");
        cv.put(LAIMU, "AUNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bibi");
        cv.put(LAIMU, "AUWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "wajan");
        cv.put(LAIMU, "AWALI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "asma");
        cv.put(LAIMU, "AUNAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ketua");
        cv.put(LAIMU, "AYYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "raja");
        cv.put(LAIMU, "AYYA");
        db.insert("kamus", INDONESIA, cv);

        // B-LAIMU //
        cv.put(INDONESIA, "azan");
        cv.put(LAIMU, "BAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bendera");
        cv.put(LAIMU, "BANDERA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rasa");
        cv.put(LAIMU, "BARASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tentara");
        cv.put(LAIMU, "BARETI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bawang");
        cv.put(LAIMU, "BAWANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bayar");
        cv.put(LAIMU, "BAYARE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "besi");
        cv.put(LAIMU, "BESI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "paman");
        cv.put(LAIMU, "BONSO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "botol");
        cv.put(LAIMU, "BOTOLO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bubur");
        cv.put(LAIMU, "BUBURE");
        db.insert("kamus", INDONESIA, cv);

        // C-LAIMU //
        cv.put(INDONESIA, "tarian khas maluku");
        cv.put(LAIMU, "CAKALELE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ulekan");
        cv.put(LAIMU, "COBE");
        db.insert("kamus", INDONESIA, cv);

        // E-LAIMU //
        cv.put(INDONESIA, "dia");
        cv.put(LAIMU, "E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sisir");
        cv.put(LAIMU, "EERUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "begitu");
        cv.put(LAIMU, "EHE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "demikian");
        cv.put(LAIMU, "EHE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "banyak");
        cv.put(LAIMU, "ELA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "besar");
        cv.put(LAIMU, "ELA'O");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "iya");
        cv.put(LAIMU, "ELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyisir");
        cv.put(LAIMU, "ERU");
        db.insert("kamus", INDONESIA, cv);

        // F-LAIMU //
        cv.put(INDONESIA, "beras");
        cv.put(LAIMU, "FALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tapak");
        cv.put(LAIMU, "FALAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membunuh");
        cv.put(LAIMU, "FAMATA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sempe");
        cv.put(LAIMU, "FANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kendi");
        cv.put(LAIMU, "FANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tangkai");
        cv.put(LAIMU, "FANEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pantat");
        cv.put(LAIMU, "FEKE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buta");
        cv.put(LAIMU, "FELE");
        db.insert("kamus", INDONESIA, cv);

        cv.put(INDONESIA, "baik");
        cv.put(LAIMU, "FIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hati-hati");
        cv.put(LAIMU, "FIA-FIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berapa");
        cv.put(LAIMU, "FILA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kelelawar");
        cv.put(LAIMU, "FINIU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memotong");
        cv.put(LAIMU, "FOFOTOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "minyak");
        cv.put(LAIMU, "FOFOTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "puasa");
        cv.put(LAIMU, "FOLI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gang");
        cv.put(LAIMU, "FOYOHOTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "minyak goreng");
        cv.put(LAIMU, "FU'UNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sedikit");
        cv.put(LAIMU, "FUFUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "semut hitam");
        cv.put(LAIMU, "FUINO");
        db.insert("kamus", INDONESIA, cv);

        // G-LAIMU //
        cv.put(INDONESIA, "gelang");
        cv.put(LAIMU, "GALANG");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gelas");
        cv.put(LAIMU, "GALASI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melinjo");
        cv.put(LAIMU, "GANEMONG");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "korek api");
        cv.put(LAIMU, "GARISI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "karet");
        cv.put(LAIMU, "GATA'A");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jambu biji");
        cv.put(LAIMU, "GIAWAS");
        db.insert("kamus", INDONESIA, cv);

        // H-LAIMU //
        cv.put(INDONESIA, "kabar");
        cv.put(LAIMU, "HABARE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "informasi");
        cv.put(LAIMU, "HABARETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pikulan");
        cv.put(LAIMU, "HAHAYALO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "babi");
        cv.put(LAIMU, "HAHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berteriak");
        cv.put(LAIMU, "HAIYALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "janda");
        cv.put(LAIMU, "HAIYO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dibelakang");
        cv.put(LAIMU, "HALEMULI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jahe");
        cv.put(LAIMU, "HALIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamis");
        cv.put(LAIMU, "HAMISI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "handuk");
        cv.put(LAIMU, "HANDOKI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "didalam");
        cv.put(LAIMU, "HANNALI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bangun");
        cv.put(LAIMU, "HANU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kemarau");
        cv.put(LAIMU, "HARATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gemuk");
        cv.put(LAIMU, "HATA LA'O");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kurus");
        cv.put(LAIMU, "HATA MELI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menarik");
        cv.put(LAIMU, "HATAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "badan");
        cv.put(LAIMU, "HATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "batu");
        cv.put(LAIMU, "HATU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "batu asa");
        cv.put(LAIMU, "HATU ASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "biji");
        cv.put(LAIMU, "HATUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menabuk");
        cv.put(LAIMU, "HAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bau");
        cv.put(LAIMU, "HAW");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mereka");
        cv.put(LAIMU, "HEHEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencari");
        cv.put(LAIMU, "HEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membuka");
        cv.put(LAIMU, "HEKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "utara");
        cv.put(LAIMU, "HELIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia");
        cv.put(LAIMU, "HEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pertama");
        cv.put(LAIMU, "MIMINAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengantar");
        cv.put(LAIMU, "HETE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "samping");
        cv.put(LAIMU, "HIANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kanan");
        cv.put(LAIMU, "HIANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mulut");
        cv.put(LAIMU, "HIHI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perempuan");
        cv.put(LAIMU, "HIHINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "selatan");
        cv.put(LAIMU, "HILAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memotong");
        cv.put(LAIMU, "HITA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengangkat");
        cv.put(LAIMU, "HITI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terkejut");
        cv.put(LAIMU, "HITITILU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dibawah");
        cv.put(LAIMU, "HIYALE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bulan");
        cv.put(LAIMU, "HIYANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "samping");
        cv.put(LAIMU, "HIYOHO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kiri");
        cv.put(LAIMU, "HIYOHO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "diatas");
        cv.put(LAIMU, "HIYOMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "panggang");
        cv.put(LAIMU, "HOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lagi");
        cv.put(LAIMU, "HOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "baru");
        cv.put(LAIMU, "HAIYO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "keluar");
        cv.put(LAIMU, "HOKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "muntah");
        cv.put(LAIMU, "HOLAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "motor");
        cv.put(LAIMU, "HONDA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rebung");
        cv.put(LAIMU, "HOONO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ngos-ngosan");
        cv.put(LAIMU, "HOSA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencabut");
        cv.put(LAIMU, "HOU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membalik");
        cv.put(LAIMU, "HOUWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pinang");
        cv.put(LAIMU, "HUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bergulir");
        cv.put(LAIMU, "HUAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ombak");
        cv.put(LAIMU, "HUAETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "arap");
        cv.put(LAIMU, "HUI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buang");
        cv.put(LAIMU, "HULAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "telanjang");
        cv.put(LAIMU, "HULALAI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menumpahkan");
        cv.put(LAIMU, "HULILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hati");
        cv.put(LAIMU, "HUTUAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang buton");
        cv.put(LAIMU, "HUTUNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buaya");
        cv.put(LAIMU, "HUAYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lubang");
        cv.put(LAIMU, "HUWOLO");
        db.insert("kamus", INDONESIA, cv);

        // I-LAIMU //
        cv.put(INDONESIA, "kenari");
        cv.put(LAIMU, "IFA'O");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "suatu hari");
        cv.put(LAIMU, "IFATO POTU LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "suatu saat");
        cv.put(LAIMU, "IFATO POTU LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sendiri");
        cv.put(LAIMU, "IISA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kita");
        cv.put(LAIMU, "IKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memarut");
        cv.put(LAIMU, "IMI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "parutan");
        cv.put(LAIMU, "IMITO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hidung");
        cv.put(LAIMU, "INTA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sekolah");
        cv.put(LAIMU, "ISKORA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "islam");
        cv.put(LAIMU, "ISLAM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang islam");
        cv.put(LAIMU, "ISLAMULU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sepatu");
        cv.put(LAIMU, "ISPATU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "penis");
        cv.put(LAIMU, "ITINO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "musim hujan");
        cv.put(LAIMU, "IWATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mendidih");
        cv.put(LAIMU, "IYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ikan");
        cv.put(LAIMU, "IYANO");
        db.insert("kamus", INDONESIA, cv);

        // J-LAIMU //
        cv.put(INDONESIA, "benang");
        cv.put(LAIMU, "JAHA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jembatan");
        cv.put(LAIMU, "JAMBATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pojok");
        cv.put(LAIMU, "JIKU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "joget");
        cv.put(LAIMU, "JOGET");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "daun tikar");
        cv.put(LAIMU, "JOHA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kolong");
        cv.put(LAIMU, "JOHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "janur");
        cv.put(LAIMU, "JOHUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kolong");
        cv.put(LAIMU, "JOJOHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melipat");
        cv.put(LAIMU, "JOU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pakaian");
        cv.put(LAIMU, "JOWAUN");
        db.insert("kamus", INDONESIA, cv);

        // K-LAIMU //
        cv.put(INDONESIA, "berjalan");
        cv.put(LAIMU, "KA'I");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kursi");
        cv.put(LAIMU, "KADERA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kenapa");
        cv.put(LAIMU, "KAEMO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melempar");
        cv.put(LAIMU, "KAHA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kehidupan");
        cv.put(LAIMU, "KEHIDUPAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lupa");
        cv.put(LAIMU, "KAHULUWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyalakan");
        cv.put(LAIMU, "KAHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "siang");
        cv.put(LAIMU, "KAKANEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pemuda");
        cv.put(LAIMU, "KAKAUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lihat");
        cv.put(LAIMU, "KAKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tingka laku");
        cv.put(LAIMU, "KALAKUAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kelakuan");
        cv.put(LAIMU, "KALAKUAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terbahak-bahak");
        cv.put(LAIMU, "KALALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "telmi");
        cv.put(LAIMU, "KALALEU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ketombe");
        cv.put(LAIMU, "KALAMUMUR");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kedua");
        cv.put(LAIMU, "KALUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lampu");
        cv.put(LAIMU, "KAMALO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ambil");
        cv.put(LAIMU, "KANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengambil");
        cv.put(LAIMU, "KANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sunami");
        cv.put(LAIMU, "KANA-KANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "talas");
        cv.put(LAIMU, "KANDAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kapal");
        cv.put(LAIMU, "KAPARU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kapas");
        cv.put(LAIMU, "KAPUSO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anting-anting");
        cv.put(LAIMU, "KARAPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menginjak");
        cv.put(LAIMU, "KARASIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kripik");
        cv.put(LAIMU, "KAREPEK");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sepeda");
        cv.put(LAIMU, "KERETA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "krupuk");
        cv.put(LAIMU, "KARUPUK");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lemari");
        cv.put(LAIMU, "KASI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kacang");
        cv.put(LAIMU, "KASIMANIRA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cermin");
        cv.put(LAIMU, "KASINAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pepaya");
        cv.put(LAIMU, "KASTERA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ketiga");
        cv.put(LAIMU, "KATIGA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cabe");
        cv.put(LAIMU, "KAUPA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "waria");
        cv.put(LAIMU, "KAWE-KAWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyembeli");
        cv.put(LAIMU, "KEHI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tahu");
        cv.put(LAIMU, "KEKEWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyobek");
        cv.put(LAIMU, "KELE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "uang");
        cv.put(LAIMU, "KEPEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "besok");
        cv.put(LAIMU, "KILA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pagi");
        cv.put(LAIMU, "KILA-KILA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tengah malam");
        cv.put(LAIMU, "KIPULAYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hujan");
        cv.put(LAIMU, "KIYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencuci");
        cv.put(LAIMU, "KOFI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kopi");
        cv.put(LAIMU, "KOFI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "patah");
        cv.put(LAIMU, "KOHA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terdampar");
        cv.put(LAIMU, "KOHOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lompat");
        cv.put(LAIMU, "KOPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lelah");
        cv.put(LAIMU, "KOWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "meneropong");
        cv.put(LAIMU, "KOWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kubur");
        cv.put(LAIMU, "KUBURO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "makam");
        cv.put(LAIMU, "KUBURO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "duduk");
        cv.put(LAIMU, "KUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "duduk-duduk");
        cv.put(LAIMU, "KUKUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menembak");
        cv.put(LAIMU, "KUNU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sepupuh jauh");
        cv.put(LAIMU, "KUSIN");
        db.insert("kamus", INDONESIA, cv);

        // L-LAIMU //
        cv.put(INDONESIA, "ruang tamu");
        cv.put(LAIMU, "LAATANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "piring");
        cv.put(LAIMU, "LA'I");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jalan");
        cv.put(LAIMU, "LAATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cara");
        cv.put(LAIMU, "LAATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menata");
        cv.put(LAIMU, "LAHAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "peduli");
        cv.put(LAIMU, "LAHAI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "baju");
        cv.put(LAIMU, "LAHITO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dua kali");
        cv.put(LAIMU, "LAI LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "satu kali");
        cv.put(LAIMU, "LAI SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tanah");
        cv.put(LAIMU, "LAITAIN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melahirkan");
        cv.put(LAIMU, "LAIYANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membara");
        cv.put(LAIMU, "LALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ikut-ikutan");
        cv.put(LAIMU, "LALAHAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "biru");
        cv.put(LAIMU, "LALAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "langit");
        cv.put(LAIMU, "LONTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "labu");
        cv.put(LAIMU, "LAPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dapur");
        cv.put(LAIMU, "LAPULO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menggiling");
        cv.put(LAIMU, "LASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jorok");
        cv.put(LAIMU, "LAU-LAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lari");
        cv.put(LAIMU, "LAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "darah");
        cv.put(LAIMU, "LAYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "merusak");
        cv.put(LAIMU, "LE'A");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "juga");
        cv.put(LAIMU, "LE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyeberang");
        cv.put(LAIMU, "LEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengusir");
        cv.put(LAIMU, "LEI-LE'I");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "samping");
        cv.put(LAIMU, "LIN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "leka-leka");
        cv.put(LAIMU, "BERGOYANG");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "miring");
        cv.put(LAIMU, "LELE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jalan kaki");
        cv.put(LAIMU, "LENA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "beri tahu");
        cv.put(LAIMU, "LEPA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lepa-lepa");
        cv.put(LAIMU, "PERAHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lese");
        cv.put(LAIMU, "KENA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sisa");
        cv.put(LAIMU, "LESIN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengadu");
        cv.put(LAIMU, "LETI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "matahari");
        cv.put(LAIMU, "LIA MATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dua ribu");
        cv.put(LAIMU, "LIHU LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tiga ribu");
        cv.put(LAIMU, "LIHU TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "seribu");
        cv.put(LAIMU, "lihun");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tangan");
        cv.put(LAIMU, "LIMAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "liman ulung");
        cv.put(LAIMU, "JARI TANGAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lina");
        cv.put(LAIMU, "BOSAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "seratus ribu");
        cv.put(LAIMU, "LIHUTUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gigi");
        cv.put(LAIMU, "LILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "merapikan");
        cv.put(LAIMU, "LILIE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lilin");
        cv.put(LAIMU, "KULIT");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gempa bumi");
        cv.put(LAIMU, "LILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sagu");
        cv.put(LAIMU, "LIPIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengeringkan");
        cv.put(LAIMU, "LO'O");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terkupas");
        cv.put(LAIMU, "LOKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencelup");
        cv.put(LAIMU, "LOLO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kotor");
        cv.put(LAIMU, "LOLOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melompat");
        cv.put(LAIMU, "LOPAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "parang");
        cv.put(LAIMU, "LOPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membungkus");
        cv.put(LAIMU, "LOSO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "didepan");
        cv.put(LAIMU, "LOTOMINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memegang");
        cv.put(LAIMU, "LOW");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jarum");
        cv.put(LAIMU, "LOWSA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "panjat");
        cv.put(LAIMU, "LU'A");
        db.insert("kamus", INDONESIA, cv);

        // M-LAIMU //
        cv.put(INDONESIA, "tukang ngantuk");
        cv.put(LAIMU, "MA'AATATULUETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tidur");
        cv.put(LAIMU, "MA'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "asam");
        cv.put(LAIMU, "MA'ALIM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "maaf");
        cv.put(LAIMU, "MAAFU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sudara");
        cv.put(LAIMU, "MAKAKAYA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tupai");
        cv.put(LAIMU, "MAKELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengunya");
        cv.put(LAIMU, "MAMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tidur-tiduran");
        cv.put(LAIMU, "MAMAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sore");
        cv.put(LAIMU, "MAMASANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mentah");
        cv.put(LAIMU, "MAMATA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamar");
        cv.put(LAIMU, "MAMATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "linggis");
        cv.put(LAIMU, "MAMOLO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "laki-laki");
        cv.put(LAIMU, "MANAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "para laki-laki");
        cv.put(LAIMU, "MANAWALU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tai ayam");
        cv.put(LAIMU, "MANTAIKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ayam");
        cv.put(LAIMU, "MANUO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ayam jago");
        cv.put(LAIMU, "MANUO GEMBA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "telur ayam");
        cv.put(LAIMU, "MANUO TEIN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengundang");
        cv.put(LAIMU, "MARSALAM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "palu");
        cv.put(LAIMU, "MARTELU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "masalah");
        cv.put(LAIMU, "MASALAH");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sarung");
        cv.put(LAIMU, "MASALIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jambu");
        cv.put(LAIMU, "MASAPANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pernikahan");
        cv.put(LAIMU, "MASASAWALO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sakit");
        cv.put(LAIMU, "MASELE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "penyakit");
        cv.put(LAIMU, "MASELEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gedung sekolah");
        cv.put(LAIMU, "MASIKORA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pahit");
        cv.put(LAIMU, "MASILA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mesin");
        cv.put(LAIMU, "MASINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mesjid");
        cv.put(LAIMU, "MASTIKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "melirik");
        cv.put(LAIMU, "MATA SILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dua mata");
        cv.put(LAIMU, "MATAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "begadang");
        cv.put(LAIMU, "MATAWANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anak");
        cv.put(LAIMU, "MAUWO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anak-anak");
        cv.put(LAIMU, "MAUWOLU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tikus");
        cv.put(LAIMU, "MAYAHA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "punya");
        cv.put(LAIMU, "MEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "milik");
        cv.put(LAIMU, "MEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "diam-diam");
        cv.put(LAIMU, "MELE-MELE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "diam");
        cv.put(LAIMU, "MELEMO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tenang");
        cv.put(LAIMU, "MELEMO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "main");
        cv.put(LAIMU, "MELEUWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bermain");
        cv.put(LAIMU, "MELEWAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kecil");
        cv.put(LAIMU, "MELI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sendiri");
        cv.put(LAIMU, "MESELEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tembok");
        cv.put(LAIMU, "MESER");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari");
        cv.put(LAIMU, "METE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hitam");
        cv.put(LAIMU, "METE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ringan");
        cv.put(LAIMU, "MIKI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jeli");
        cv.put(LAIMU, "MIKI-MIKI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cekatan");
        cv.put(LAIMU, "MIKI-MIKI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kebun");
        cv.put(LAIMU, "MILIM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pertama");
        cv.put(LAIMU, "MIMINAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dingin");
        cv.put(LAIMU, "MOKI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mangkok");
        cv.put(LAIMU, "MOKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tenggelam");
        cv.put(LAIMU, "MOKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "belut");
        cv.put(LAIMU, "MOREA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kapal kecil");
        cv.put(LAIMU, "MOTORO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gila");
        cv.put(LAIMU, "MUIKELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "malu");
        cv.put(LAIMU, "MUILA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "matang");
        cv.put(LAIMU, "MULA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "keponakan");
        cv.put(LAIMU, "MULI'U");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengaji");
        cv.put(LAIMU, "MUSUPURU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pengajian");
        cv.put(LAIMU, "MUSUPURUTO");
        db.insert("kamus", INDONESIA, cv);

        // N-LAIMU //
        cv.put(INDONESIA, "cepat sekali");
        cv.put(LAIMU, "NA'OI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "negeri");
        cv.put(LAIMU, "NAGRI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memancing");
        cv.put(LAIMU, "NAHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "merayap");
        cv.put(LAIMU, "NALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tahun");
        cv.put(LAIMU, "NALIO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "enak");
        cv.put(LAIMU, "NANAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gula");
        cv.put(LAIMU, "NASU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lahir");
        cv.put(LAIMU, "NAUHATU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "merangkak");
        cv.put(LAIMU, "NESA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ular");
        cv.put(LAIMU, "NIFA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bermimpi");
        cv.put(LAIMU, "NINIFI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kunyit");
        cv.put(LAIMU, "NINO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia punya");
        cv.put(LAIMU, "NIWEI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "itu");
        cv.put(LAIMU, "NOM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kelapa");
        cv.put(LAIMU, "NUELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pulau");
        cv.put(LAIMU, "NUSA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "masuk");
        cv.put(LAIMU, "NUSU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "meminang");
        cv.put(LAIMU, "NUSU PASUA");
        db.insert("kamus", INDONESIA, cv);

        // O-LAIMU //
        cv.put(INDONESIA, "obat");
        cv.put(LAIMU, "OBATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cepat");
        cv.put(LAIMU, "OI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cepat-cepat");
        cv.put(LAIMU, "OI-OI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berdiri");
        cv.put(LAIMU, "OLO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencukur");
        cv.put(LAIMU, "OMO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bisu");
        cv.put(LAIMU, "OMOU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bisuan");
        cv.put(LAIMU, "OMOUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kudis");
        cv.put(LAIMU, "OPU-OPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jam");
        cv.put(LAIMU, "ORASI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mobil");
        cv.put(LAIMU, "OTO");
        db.insert("kamus", INDONESIA, cv);

        // P-LAIMU //
        cv.put(INDONESIA, "berbohong");
        cv.put(LAIMU, "PA'AKALE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kue sagu");
        cv.put(LAIMU, "PA'U");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bayam");
        cv.put(LAIMU, "PAENO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mangga");
        cv.put(LAIMU, "PAHARO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memaki");
        cv.put(LAIMU, "PAHULA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyembunyikan");
        cv.put(LAIMU, "PAHUNUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tikar");
        cv.put(LAIMU, "PAILO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buang air besar");
        cv.put(LAIMU, "PAINE'I");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "begitu");
        cv.put(LAIMU, "PAINOM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buang air kecil");
        cv.put(LAIMU, "PAITILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pilih");
        cv.put(LAIMU, "PAKAILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memakai");
        cv.put(LAIMU, "PAKE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berbicara");
        cv.put(LAIMU, "PAKEKE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dinding belakang rumah");
        cv.put(LAIMU, "PAKELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gelap");
        cv.put(LAIMU, "PAKIMOLO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menjemur");
        cv.put(LAIMU, "PAKUNU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menjual");
        cv.put(LAIMU, "PALAHILIE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "marah");
        cv.put(LAIMU, "PALAMANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membagi");
        cv.put(LAIMU, "PALAWA'U");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pamali");
        cv.put(LAIMU, "PALI'ANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyaksikan");
        cv.put(LAIMU, "PALIHAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memasak");
        cv.put(LAIMU, "PAMASA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "masakan");
        cv.put(LAIMU, "PAMASATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memanah");
        cv.put(LAIMU, "PANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencuri");
        cv.put(LAIMU, "PANANAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "roket");
        cv.put(LAIMU, "PANCAR GAS");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "singkong");
        cv.put(LAIMU, "PANGKARA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gagang");
        cv.put(LAIMU, "PANON");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berteduh");
        cv.put(LAIMU, "PANTILU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bayangan pohon");
        cv.put(LAIMU, "PANTULUETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "minta");
        cv.put(LAIMU, "PANUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saling memaki");
        cv.put(LAIMU, "PAPAHULA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tusuk konde");
        cv.put(LAIMU, "PAPAKUDA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cabut");
        cv.put(LAIMU, "PAPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kembar");
        cv.put(LAIMU, "PAR-PAR");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "panci");
        cv.put(LAIMU, "PARIU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saling tembak");
        cv.put(LAIMU, "PARKUKUNU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "malas");
        cv.put(LAIMU, "PASAKALE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nikah");
        cv.put(LAIMU, "PASAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kawin");
        cv.put(LAIMU, "PASAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "miminta");
        cv.put(LAIMU, "PASUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menagis");
        cv.put(LAIMU, "PATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ribut");
        cv.put(LAIMU, "PATATIE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memasukan");
        cv.put(LAIMU, "PATAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lambat");
        cv.put(LAIMU, "PENEWAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengupas");
        cv.put(LAIMU, "PESI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "punggung");
        cv.put(LAIMU, "PEU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "capek");
        cv.put(LAIMU, "PILI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buat");
        cv.put(LAIMU, "PINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menjadi");
        cv.put(LAIMU, "PINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nenek");
        cv.put(LAIMU, "PINANTUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berkeringat");
        cv.put(LAIMU, "POESAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menelan");
        cv.put(LAIMU, "POKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kuning");
        cv.put(LAIMU, "POKU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kasihan");
        cv.put(LAIMU, "POLOKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pacaran");
        cv.put(LAIMU, "POLOLOMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "meremas");
        cv.put(LAIMU, "POSO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kadal");
        cv.put(LAIMU, "PUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cengkih");
        cv.put(LAIMU, "PUROWANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "puser");
        cv.put(LAIMU, "PUSEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "selesai");
        cv.put(LAIMU, "PUSIE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menerobos");
        cv.put(LAIMU, "PUSU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "busuk");
        cv.put(LAIMU, "PUTA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sembarangan");
        cv.put(LAIMU, "PUTAEMO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "panas");
        cv.put(LAIMU, "PUTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mendengar");
        cv.put(LAIMU, "PUTULUE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gerah");
        cv.put(LAIMU, "PUTUTO");
        db.insert("kamus", INDONESIA, cv);

        // Q-LAIMU //
        cv.put(INDONESIA, "al-qur'an");
        cv.put(LAIMU, "QUR'AN");
        db.insert("kamus", INDONESIA, cv);

        // R-LAIMU //
        cv.put(INDONESIA, "rakyat");
        cv.put(LAIMU, "RA'YATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rebana");
        cv.put(LAIMU, "RABANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "radio");
        cv.put(LAIMU, "RADIO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rambutan");
        cv.put(LAIMU, "RAMBUTAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rabu");
        cv.put(LAIMU, "ROBO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ban");
        cv.put(LAIMU, "RODA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rombongan");
        cv.put(LAIMU, "ROMBONGAN");
        db.insert("kamus", INDONESIA, cv);

        // S-LAIMU //
        cv.put(INDONESIA, "naik");
        cv.put(LAIMU, "SA'A");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencampur");
        cv.put(LAIMU, "SAEELA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membeli");
        cv.put(LAIMU, "SAHE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tegur");
        cv.put(LAIMU, "SAHOLA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jaga");
        cv.put(LAIMU, "SAKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nanti");
        cv.put(LAIMU, "SAKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "coklat");
        cv.put(LAIMU, "SAKARATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "selamat");
        cv.put(LAIMU, "SALAMAT");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sendal");
        cv.put(LAIMU, "SANDALI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menutup");
        cv.put(LAIMU, "SAPA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sepatu");
        cv.put(LAIMU, "SAPATU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kristen");
        cv.put(LAIMU, "SARANE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang kristen");
        cv.put(LAIMU, "SARANELU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ranjau");
        cv.put(LAIMU, "SASAUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "semuanya");
        cv.put(LAIMU, "SESEUWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "semua");
        cv.put(LAIMU, "SEUWE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kuncing");
        cv.put(LAIMU, "SI'A");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buka puasa");
        cv.put(LAIMU, "SIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "gayung");
        cv.put(LAIMU, "SIBUR");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menendang");
        cv.put(LAIMU, "SIKU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sinar");
        cv.put(LAIMU, "SINA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cina");
        cv.put(LAIMU, "sina");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang cina");
        cv.put(LAIMU, "SINALU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "semberono");
        cv.put(LAIMU, "SIULAKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tempurung");
        cv.put(LAIMU, "SOKAHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menyiram");
        cv.put(LAIMU, "SOLA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mandi");
        cv.put(LAIMU, "SOLI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sendok");
        cv.put(LAIMU, "SONDO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sholat");
        cv.put(LAIMU, "SOPAYANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sumbat");
        cv.put(LAIMU, "SOSO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bahasa");
        cv.put(LAIMU, "SOU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "patah");
        cv.put(LAIMU, "SU'A");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sukun");
        cv.put(LAIMU, "SU'UNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mundur");
        cv.put(LAIMU, "SUAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menjolok");
        cv.put(LAIMU, "SULI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "manis");
        cv.put(LAIMU, "SUMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mencium");
        cv.put(LAIMU, "SUMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "membakar");
        cv.put(LAIMU, "SUPALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "surat");
        cv.put(LAIMU, "SURATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sirsak");
        cv.put(LAIMU, "SIRIWARATA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berenang");
        cv.put(LAIMU, "SUSU'U");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kunci");
        cv.put(LAIMU, "SUSUAN");
        db.insert("kamus", INDONESIA, cv);

        // T-LAIMU //
        cv.put(INDONESIA, "tangkap");
        cv.put(LAIMU, "TADA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "telepon");
        cv.put(LAIMU, "TALIPON");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kapak");
        cv.put(LAIMU, "TAMAANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menamatkan");
        cv.put(LAIMU, "TAMATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berantakan");
        cv.put(LAIMU, "TAPARAKUNA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terong");
        cv.put(LAIMU, "TARUNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sambal");
        cv.put(LAIMU, "TASIO KAUWO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "becek");
        cv.put(LAIMU, "TATANEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tungku");
        cv.put(LAIMU, "TATUNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "penuh");
        cv.put(LAIMU, "TAUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "air laut");
        cv.put(LAIMU, "TAWAEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "buncit");
        cv.put(LAIMU, "TEHUN REBANA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kenyang");
        cv.put(LAIMU, "TEHUN PISA");
        db.insert("kamus", INDONESIA, cv);

        cv.put(INDONESIA, "nampan");
        cv.put(LAIMU, "TEPSI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memotong kayu");
        cv.put(LAIMU, "TETA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "berjalan");
        cv.put(LAIMU, "TITA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tulang");
        cv.put(LAIMU, "TO'IN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tebu");
        cv.put(LAIMU, "TOHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "toples");
        cv.put(LAIMU, "TOPLES");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ujung");
        cv.put(LAIMU, "TOTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bunyi");
        cv.put(LAIMU, "TU'UN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menukar");
        cv.put(LAIMU, "TUKARE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lutut");
        cv.put(LAIMU, "TULEN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "durian");
        cv.put(LAIMU, "TULENO");
        db.insert("kamus", INDONESIA, cv);

        // U-LAIMU //
        cv.put(INDONESIA, "pewawat");
        cv.put(LAIMU, "UDARA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "wajah");
        cv.put(LAIMU, "UFA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ikan teri");
        cv.put(LAIMU, "UFUNO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sabut kelapa");
        cv.put(LAIMU, "UFUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jamur");
        cv.put(LAIMU, "UJATO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kepala");
        cv.put(LAIMU, "UJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rambut");
        cv.put(LAIMU, "UJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rumah");
        cv.put(LAIMU, "UMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bintang");
        cv.put(LAIMU, "UMARENO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kambing");
        cv.put(LAIMU, "UNE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang gunung");
        cv.put(LAIMU, "UPAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "siput");
        cv.put(LAIMU, "UPATU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "cucu");
        cv.put(LAIMU, "UPU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jeruk");
        cv.put(LAIMU, "USI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sayur");
        cv.put(LAIMU, "UTANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "banbu");
        cv.put(LAIMU, "UTEO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kutu");
        cv.put(LAIMU, "UTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "batuk");
        cv.put(LAIMU, "UUSE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pembekalan");
        cv.put(LAIMU, "UWEKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bekal");
        cv.put(LAIMU, "UWEKA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "penyakitan");
        cv.put(LAIMU, "UYAYALE");
        db.insert("kamus", INDONESIA, cv);

        // V-LAIMU //
        cv.put(INDONESIA, "baik");
        cv.put(LAIMU, "VIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jenis kelamin perempuan");
        cv.put(LAIMU, "VIINO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kelelawar");
        cv.put(LAIMU, "VINIU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sampah");
        cv.put(LAIMU, "VOFIO");
        db.insert("kamus", INDONESIA, cv);

        // W-LAIMU //
        cv.put(INDONESIA, "air");
        cv.put(LAIMU, "WAELO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "wakano");
        cv.put(LAIMU, "BANDA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang banda");
        cv.put(LAIMU, "WAKANOLU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mengorek");
        cv.put(LAIMU, "WALA-WALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memukul");
        cv.put(LAIMU, "WALU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "belanda");
        cv.put(LAIMU, "WARATA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang belanda");
        cv.put(LAIMU, "WARATALU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anjing");
        cv.put(LAIMU, "WASU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sumpit");
        cv.put(LAIMU, "WATANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "menunggu");
        cv.put(LAIMU, "WAWALE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "memutar");
        cv.put(LAIMU, "WAY");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bergerak");
        cv.put(LAIMU, "WAY-WAI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "urat");
        cv.put(LAIMU, "WAYAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hambur");
        cv.put(LAIMU, "WELAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hilang");
        cv.put(LAIMU, "WELAETI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ilalang");
        cv.put(LAIMU, "WELI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pacar");
        cv.put(LAIMU, "WESILO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kekasih");
        cv.put(LAIMU, "WESILO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tempat");
        cv.put(LAIMU, "WOTON");
        db.insert("kamus", INDONESIA, cv);

        // Y-LAIMU //
        cv.put(INDONESIA, "berbunyi");
        cv.put(LAIMU, "YAFAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tungku masak");
        cv.put(LAIMU, "YAFU MATAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "terbakar");
        cv.put(LAIMU, "YAFU PUTUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "angin");
        cv.put(LAIMU, "YAHANO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saya");
        cv.put(LAIMU, "YAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "aku");
        cv.put(LAIMU, "YAU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pagar");
        cv.put(LAIMU, "YAYO");
        db.insert("kamus", INDONESIA, cv);

        //KATA DAN KALIMAT//
        //KALIMAT//
        cv.put(INDONESIA, "Saya bagun");
        cv.put(LAIMU, "AHANU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saya bagun tidur");
        cv.put(LAIMU, "AHANU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "makanan diatas meja");
        cv.put(LAIMU, "A AELO ALA MEJA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "agama kamu apa");
        cv.put(LAIMU, "YALE MEI AGAMA SAIM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari minggu");
        cv.put(LAIMU, "SALA METE IN METE AHAD");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari senin");
        cv.put(LAIMU, "SALA METE IN METE SENIN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari selasa");
        cv.put(LAIMU, "SALA METE IN METE SELAS");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari rabu");
        cv.put(LAIMU, "SALA METE IN METE RABU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari kamis");
        cv.put(LAIMU, "SALA METE IN METE HAMISI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari jumat");
        cv.put(LAIMU, "SALA METE IN METE JUMAATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "hari ini hari sabtu");
        cv.put(LAIMU, "SALA METE IN METE SABDUH");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nene itu tinggal digubuk");
        cv.put(LAIMU, "ANENE MITI KUE ALA AHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kakek itu tinggal digubuk");
        cv.put(LAIMU, "ATETE MITI KUE ALA AHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mama itu tinggal digubuk");
        cv.put(LAIMU, "AMAMA MITI KUE ALA AHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bapak itu tinggal digubuk");
        cv.put(LAIMU, "ABAPA MITI KUE ALA AHAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kalian berbuat untuk akhirat kalian");
        cv.put(LAIMU, "YEM PINA KA YEM MEI AKHIRATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang itu membuang lendirnya");
        cv.put(LAIMU, "MANSIA MITI HULAE NI AKALAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "orang itu terkena flu");
        cv.put(LAIMU, "MANSIA MITI AKINONOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "pucuk daun singkong");
        cv.put(LAIMU, "PANGKALA AKUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia makan nasi");
        cv.put(LAIMU, "E AE FALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia makan nasi hagus");
        cv.put(LAIMU, "E AE FALA ALAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saya tidur dengan bantal");
        cv.put(LAIMU, "A MAE ALA ALAJUHU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamu jangan menghina orang");
        cv.put(LAIMU, "O ALANA MANSIA TE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamu beristirahat sebentar");
        cv.put(LAIMU, "OALIE FUFUN SAN LE'ENA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "raja itu mengumpulkan perangkat desanya");
        cv.put(LAIMU, "AYYA MITI E LOFUE NI ALOONOLU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamu menulis catatan");
        cv.put(LAIMU, "O ALUE ALUETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "nenek itu makan pinang dan siri");
        cv.put(LAIMU, "ANENE MITI E AE HUA TIA SIRI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ibu itu memasak didapur");
        cv.put(LAIMU, "AMAMA MITI PAMASA ALA DAPURO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "mendengar azan di mesjid");
        cv.put(LAIMU, "PUTULUE BAN ALA MASTIKO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bendera kita adalah merah putih");
        cv.put(LAIMU, "KO KUWEI BENDERA NA PUTIO TIA KAUWO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "rasa mangga ini manis sekali");
        cv.put(LAIMU, "PAHARO IN SUMA ELA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anaknya menjadi tentara");
        cv.put(LAIMU, "ANAN PINA BARETI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "harga bawang merah dipasar naik lagi");
        cv.put(LAIMU, "BAWANO KAUWO ALA PASAR HELIN SAA HOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia membayar utangnya");
        cv.put(LAIMU, "E BAYARE NI UTAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "paman pergi ke kebun");
        cv.put(LAIMU, "ABONGSO E KAI ALA MILIM");
        db.insert("kamus", INDONESIA, cv);
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "parang itu terbuat dari besi");
        cv.put(LAIMU, "LOPU MITI PINATI HAILIE BESI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "botol itu pecah");
        cv.put(LAIMU, "BOTOLO MITI PISATI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saya sedang makan bubur");
        cv.put(LAIMU, "YAU AE BUBURE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lima buah Buku");
        cv.put(LAIMU, "BUKU HUAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia menyaksikan cakalele dilapangan");
        cv.put(LAIMU, "E PALIHAE CAKALELE ALA TEREM");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ibu mempunyai cobe baru");
        cv.put(LAIMU, "AMAMA NIWEI COBE HOIYO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perempuan itu membeli sisir");
        cv.put(LAIMU, "HIHINA MITI SAHE EERUTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "anak itu banyak berpuasa");
        cv.put(LAIMU, "MAUWO MITI FOLI ELA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia mengambil batu besar");
        cv.put(LAIMU, "EKANA HATU ELA'O");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia pergi ke ambon");
        cv.put(LAIMU, "E KAI ALA AMBON");
        db.insert("kamus", INDONESIA, cv);
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perempuan itu menyisir rambutnya");
        cv.put(LAIMU, "HIHINA MITI E ERU NI UJUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "ibu memasak nasi");
        cv.put(LAIMU, "AMAMA E TATU FALA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tapak tangan");
        cv.put(LAIMU, "YAI FALAN");
        cv.put(INDONESIA, "membunuh orang");
        cv.put(LAIMU, "FAMATA MANSIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "laki-laki itu membunuh orang");
        cv.put(LAIMU, "MANAWA MITI FAMATA MANSIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bapak itu memukul anaknya");
        cv.put(LAIMU, "APAPA MITI E WALU ANAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perempuan itu cantik sekali");
        cv.put(LAIMU, "HIHINA MITI EFIYAI ELA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia menunggu pacarnya di gang");
        cv.put(LAIMU, "E WALELE'E NI WISILO ALA FOYOHOTO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "perempuan itu memekai gelang");
        cv.put(LAIMU, "HIHINA MITI PAKE'E GALANG");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia minum air");
        cv.put(LAIMU, "E SE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia minum air dengan gelas");
        cv.put(LAIMU, "E SE'E TIA GALASI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "jangan gitu");
        cv.put(LAIMU, "PAIM TE'E");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "bagaimana kabar kamu");
        cv.put(LAIMU, "YALE HABARE PALAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kabar baik");
        cv.put(LAIMU, "HABARE FIA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "saya mendengar informasi");
        cv.put(LAIMU, "APUTULUE HABARETO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia menikah");
        cv.put(LAIMU, "E PASAWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia menikahi janda");
        cv.put(LAIMU, "E PASAWA TA HAIYO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dia berdiri dibelakang pintu");
        cv.put(LAIMU, "E OLO ALA HALIMULI TANJUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kamu pergi sendiri");
        cv.put(LAIMU, "O KAI IISAO");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "kita semua");
        cv.put(LAIMU, "IKO SEWEKO");
        db.insert("kamus", INDONESIA, cv);

        //ANGKA/
        cv.put(INDONESIA, "satu");
        cv.put(LAIMU, "SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "1");
        cv.put(LAIMU, "SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "dua");
        cv.put(LAIMU, "lua");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "2");
        cv.put(LAIMU, "LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tiga");
        cv.put(LAIMU, "TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "3");
        cv.put(LAIMU, "TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "empat");
        cv.put(LAIMU, "VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "4");
        cv.put(LAIMU, "VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "lima");
        cv.put(LAIMU, "LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "5");
        cv.put(LAIMU, "LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "enam");
        cv.put(LAIMU, "NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "6");
        cv.put(LAIMU, "NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "tujuh");
        cv.put(LAIMU, "FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "7");
        cv.put(LAIMU, "FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "delapan");
        cv.put(LAIMU, "WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "8");
        cv.put(LAIMU, "WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sembilan");
        cv.put(LAIMU, "SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "9");
        cv.put(LAIMU, "SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "sepuluh");
        cv.put(LAIMU, "HUTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "10");
        cv.put(LAIMU, "HUTU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "11");
        cv.put(LAIMU, "HUTU SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "12");
        cv.put(LAIMU, "HUTU SAN LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "13");
        cv.put(LAIMU, "HUTU SAN LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "14");
        cv.put(LAIMU, "HUTU SAN LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "15");
        cv.put(LAIMU, "HUTU SAN LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "16");
        cv.put(LAIMU, "HUTU SAN LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "17");
        cv.put(LAIMU, "HUTU SAN LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "18");
        cv.put(LAIMU, "HUTU SAN LAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "19");
        cv.put(LAIMU, "HUTU SAN LAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "20");
        cv.put(LAIMU, "HUTU LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "21");
        cv.put(LAIMU, "HUTU LUA LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "22");
        cv.put(LAIMU, "HUTU LUA LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "23");
        cv.put(LAIMU, "HUTU LUA LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "24");
        cv.put(LAIMU, "HUTU LUA LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "25");
        cv.put(LAIMU, "HUTU LUA LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "26");
        cv.put(LAIMU, "HUTU LUA LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "27");
        cv.put(LAIMU, "HUTU LUA LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "28");
        cv.put(LAIMU, "HUTU LUA ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "29");
        cv.put(LAIMU, "HUTU LUA LAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "30");
        cv.put(LAIMU, "HUTU TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "31");
        cv.put(LAIMU, "HUTU TOI LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "32");
        cv.put(LAIMU, "HUTU TOI LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "33");
        cv.put(LAIMU, "HUTU TOI LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "34");
        cv.put(LAIMU, "HUTU TOI LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "35");
        cv.put(LAIMU, "HUTU TOI LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "36");
        cv.put(LAIMU, "HUTU TOI LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "37");
        cv.put(LAIMU, "HUTU TOI LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "38");
        cv.put(LAIMU, "HUTU TOI ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "39");
        cv.put(LAIMU, "HUTU TOI ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "40");
        cv.put(LAIMU, "HUTU VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "41");
        cv.put(LAIMU, "HUTU VAE LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "42");
        cv.put(LAIMU, "HUTU VAE LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "43");
        cv.put(LAIMU, "HUTU VAE LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "44");
        cv.put(LAIMU, "HUTU VAE LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "45");
        cv.put(LAIMU, "HUTU VAE LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "46");
        cv.put(LAIMU, "HUTU VAE LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "47");
        cv.put(LAIMU, "HUTU VAE LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "48");
        cv.put(LAIMU, "HUTU VAE ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "49");
        cv.put(LAIMU, "HUTU VAE ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "50");
        cv.put(LAIMU, "HUTU LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "51");
        cv.put(LAIMU, "HUTU LIMA LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "52");
        cv.put(LAIMU, "HUTU LIMA LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "53");
        cv.put(LAIMU, "HUTU LIMA LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "54");
        cv.put(LAIMU, "HUTU LIMA LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "55");
        cv.put(LAIMU, "HUTU LIMA LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "56");
        cv.put(LAIMU, "HUTU LIMA LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "57");
        cv.put(LAIMU, "HUTU LIMA LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "58");
        cv.put(LAIMU, "HUTU LIMA ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "59");
        cv.put(LAIMU, "HUTU SIWA ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "60");
        cv.put(LAIMU, "HUTU NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "61");
        cv.put(LAIMU, "HUTU NOE LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "62");
        cv.put(LAIMU, "HUTU NOE LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "63");
        cv.put(LAIMU, "HUTU NOE LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "64");
        cv.put(LAIMU, "HUTU NOE LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "65");
        cv.put(LAIMU, "HUTU NOE LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "66");
        cv.put(LAIMU, "HUTU NOE LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "67");
        cv.put(LAIMU, "HUTU NOE LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "68");
        cv.put(LAIMU, "HUTU NOE ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "69");
        cv.put(LAIMU, "HUTU NOE ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "70");
        cv.put(LAIMU, "HUTU FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "71");
        cv.put(LAIMU, "HUTU FITU LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "72");
        cv.put(LAIMU, "HUTU FITU LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "73");
        cv.put(LAIMU, "HUTU FITU LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "74");
        cv.put(LAIMU, "HUTU FITU LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "75");
        cv.put(LAIMU, "HUTU FITU LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "76");
        cv.put(LAIMU, "HUTU FITU LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "77");
        cv.put(LAIMU, "HUTU FITU LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "78");
        cv.put(LAIMU, "HUTU FITU ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "79");
        cv.put(LAIMU, "HUTU FITU ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "80");
        cv.put(LAIMU, "HUTU WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "81");
        cv.put(LAIMU, "HUTU WAJU LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "82");
        cv.put(LAIMU, "HUTU WAJU LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "83");
        cv.put(LAIMU, "HUTU WAJU LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "84");
        cv.put(LAIMU, "HUTU WAJU LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "85");
        cv.put(LAIMU, "HUTU WAJU LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "86");
        cv.put(LAIMU, "HUTU WAJU LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "87");
        cv.put(LAIMU, "HUTU WAJU LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "88");
        cv.put(LAIMU, "HUTU WAJU ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "89");
        cv.put(LAIMU, "HUTU WAJU ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "90");
        cv.put(LAIMU, "HUTU SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "91");
        cv.put(LAIMU, "HUTU SIWA LAN SAN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "92");
        cv.put(LAIMU, "HUTU SIWA LAN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "93");
        cv.put(LAIMU, "HUTU SIWA LAN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "94");
        cv.put(LAIMU, "HUTU SIWA LAN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "95");
        cv.put(LAIMU, "HUTU SIWA LAN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "96");
        cv.put(LAIMU, "HUTU SIWA LAN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "97");
        cv.put(LAIMU, "HUTU SIWA LAN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "98");
        cv.put(LAIMU, "HUTU SIWA ALAN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "99");
        cv.put(LAIMU, "HUTU SIWA ALAN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "100");
        cv.put(LAIMU, "UTUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "200");
        cv.put(LAIMU, "UTUN LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "300");
        cv.put(LAIMU, "UTUN TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "400");
        cv.put(LAIMU, "UTUN VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "500");
        cv.put(LAIMU, "UTUN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "600");
        cv.put(LAIMU, "UTUN NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "700");
        cv.put(LAIMU, "UTUN FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "800");
        cv.put(LAIMU, "UTUN WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "900");
        cv.put(LAIMU, "UTUN SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "1000");
        cv.put(LAIMU, "LIHUN");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "1500");
        cv.put(LAIMU, "LIHU UTUN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "2000");
        cv.put(LAIMU, "LIHU LUA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "2500");
        cv.put(LAIMU, "LIHU LUA UTUN LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "3000");
        cv.put(LAIMU, "LIHU TOI");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "4000");
        cv.put(LAIMU, "LIHU VAE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "5000");
        cv.put(LAIMU, "LIHU LIMA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "6000");
        cv.put(LAIMU, "LIHU NOE");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "7000");
        cv.put(LAIMU, "LIHU FITU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "8000");
        cv.put(LAIMU, "LIHU WAJU");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "9000");
        cv.put(LAIMU, "LIHU SIWA");
        db.insert("kamus", INDONESIA, cv);
        cv.put(INDONESIA, "10.000");
        cv.put(LAIMU, "LIHUUTUN");
        db.insert("kamus", INDONESIA, cv);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    }

    @Override

    public void onCreate(SQLiteDatabase db) {
    }
}
